# Generated by Django 3.2 on 2023-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Open', 'Open'), ('Scheduled', 'Scheduled'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Sent', max_length=25),
        ),
    ]
