# Generated by Django 3.2 on 2023-04-29 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor_request', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
