# Generated by Django 3.2 on 2023-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('borough', models.CharField(choices=[('Manhattan', 'Manhattan'), ('Brooklyn', 'Brooklyn'), ('Queens', 'Queens'), ('Bronx', 'Bronx'), ('Staten Island', 'Staten Island')], max_length=15)),
                ('type', models.CharField(choices=[('NYC Smart Bin', 'NYC Smart Bin'), ('NYC Community Site', 'NYC Community Site'), ('User Listing', 'User Listing')], max_length=30)),
                ('season', models.CharField(choices=[('Year Round', 'Year Round'), ('Seasonal', 'Seasonal')], max_length=15)),
                ('is_always_open', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
