# Generated by Django 3.2 on 2023-04-25 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSchedule',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dropoff_locator.site')),
                ('mon', models.CharField(max_length=55, null=True)),
                ('tues', models.CharField(max_length=55, null=True)),
                ('wed', models.CharField(max_length=55, null=True)),
                ('thurs', models.CharField(max_length=55, null=True)),
                ('fri', models.CharField(max_length=55, null=True)),
                ('sat', models.CharField(max_length=55, null=True)),
                ('sun', models.CharField(max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSeason',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dropoff_locator.site')),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
            ],
        ),
    ]
