# Generated by Django 3.2 on 2023-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locator', '0003_auto_20230427_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptedItems',
            new_name='SiteAccepted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(choices=[(1, 'Fruit and vegetable scraps, eggshells, nuts'), (2, 'Rice, pasta, bread, grains, cereal'), (3, 'Beans, flour, spices'), (4, 'Meat, fish, dairy, whole eggs, bones'), (5, 'Fat, oil, greasy food scraps'), (6, 'Paper products, pizza boxes'), (7, 'Coffee grounds, tea bags'), (8, 'Plant and yard waste'), (9, 'Commercial food scraps')], primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='siteaccepted',
            unique_together={('site', 'item')},
        ),
    ]
