# Generated by Django 3.2 on 2023-04-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locator', '0004_auto_20230427_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='season',
            field=models.CharField(choices=[('Year Round', 'Year Round'), ('Seasonal', 'Seasonal'), ('User', 'User')], max_length=15),
        ),
    ]
