# Generated by Django 3.2 on 2023-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locator', '0005_auto_20230429_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='season',
            field=models.CharField(choices=[('Year Round', 'Year Round'), ('Seasonal', 'Seasonal'), ('User', 'User')], default='User Listing', max_length=15),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('NYC Smart Bin', 'NYC Smart Bin'), ('NYC Community Site', 'NYC Community Site'), ('User Listing', 'User Listing')], default='User', max_length=30),
        ),
    ]
